//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFCTerrainGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IFCTerrainGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Choose file ähnelt.
        /// </summary>
        internal static string btnChoose {
            get {
                return ResourceManager.GetString("btnChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convert to TIN ähnelt.
        /// </summary>
        internal static string btnConvert {
            get {
                return ResourceManager.GetString("btnConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Exit ähnelt.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Input ähnelt.
        /// </summary>
        internal static string btnInput {
            get {
                return ResourceManager.GetString("btnInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Output ähnelt.
        /// </summary>
        internal static string btnOutput {
            get {
                return ResourceManager.GetString("btnOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Read ähnelt.
        /// </summary>
        internal static string btnRead {
            get {
                return ResourceManager.GetString("btnRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Read file ähnelt.
        /// </summary>
        internal static string btnReadFile {
            get {
                return ResourceManager.GetString("btnReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Settings ähnelt.
        /// </summary>
        internal static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Write IFC ähnelt.
        /// </summary>
        internal static string btnWrite {
            get {
                return ResourceManager.GetString("btnWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate Points on Breaklines ähnelt.
        /// </summary>
        internal static string chkReplace {
            get {
                return ResourceManager.GetString("chkReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Z-Origin = 0 ähnelt.
        /// </summary>
        internal static string chkZ {
            get {
                return ResourceManager.GetString("chkZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DD_BIM_LOGO {
            get {
                object obj = ResourceManager.GetObject("DD_BIM_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File: {0} is not readable. ähnelt.
        /// </summary>
        internal static string errFileNotReadable {
            get {
                return ResourceManager.GetString("errFileNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Layer contains no line data. ähnelt.
        /// </summary>
        internal static string errNoLineData {
            get {
                return ResourceManager.GetString("errNoLineData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File {0} contains no TIN. ähnelt.
        /// </summary>
        internal static string errNoTIN {
            get {
                return ResourceManager.GetString("errNoTIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TIN in File {0} contains no readable data. ähnelt.
        /// </summary>
        internal static string errNoTINData {
            get {
                return ResourceManager.GetString("errNoTINData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editor ähnelt.
        /// </summary>
        internal static string gpEditor {
            get {
                return ResourceManager.GetString("gpEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Terrain ähnelt.
        /// </summary>
        internal static string gpFile {
            get {
                return ResourceManager.GetString("gpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menu ähnelt.
        /// </summary>
        internal static string gpMenu {
            get {
                return ResourceManager.GetString("gpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messages ähnelt.
        /// </summary>
        internal static string gpMsg {
            get {
                return ResourceManager.GetString("gpMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Site origin ähnelt.
        /// </summary>
        internal static string gpOrigin {
            get {
                return ResourceManager.GetString("gpOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff31507\deff0\stshfdbch31506\stshfloch31506\stshfhich31506\stshfbi31507\deflang1033\deflangfe1033\themelang1031\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}
        ///{\f44\fbidi \fswiss\fcharset134\fprq2{\*\panose 020b0503020204020204}Microsoft YaHei;}{\f87\fbidi \fswiss\fcharset134\fprq2 @Microsoft YaHei;}{\flomajor\f31500\f [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string IFCTerrain {
            get {
                return ResourceManager.GetString("IFCTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company ähnelt.
        /// </summary>
        internal static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count ähnelt.
        /// </summary>
        internal static string lblCount {
            get {
                return ResourceManager.GetString("lblCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die with distance ähnelt.
        /// </summary>
        internal static string lblDist {
            get {
                return ResourceManager.GetString("lblDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extent ähnelt.
        /// </summary>
        internal static string lblExtent {
            get {
                return ResourceManager.GetString("lblExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Family name ähnelt.
        /// </summary>
        internal static string lblFamily {
            get {
                return ResourceManager.GetString("lblFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File name ähnelt.
        /// </summary>
        internal static string lblFile {
            get {
                return ResourceManager.GetString("lblFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Given name ähnelt.
        /// </summary>
        internal static string lblGiven {
            get {
                return ResourceManager.GetString("lblGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Horizon: ähnelt.
        /// </summary>
        internal static string lblHorizon {
            get {
                return ResourceManager.GetString("lblHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project name ähnelt.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimal point distance ähnelt.
        /// </summary>
        internal static string lblPtDist {
            get {
                return ResourceManager.GetString("lblPtDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File type ähnelt.
        /// </summary>
        internal static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Points: {0} Lines: {1} Faces: {2} ähnelt.
        /// </summary>
        internal static string msgCount {
            get {
                return ResourceManager.GetString("msgCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Horizon successfull read. ähnelt.
        /// </summary>
        internal static string msgHorizonSuccess {
            get {
                return ResourceManager.GetString("msgHorizonSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layer successfull read. ähnelt.
        /// </summary>
        internal static string msgLayerSucces {
            get {
                return ResourceManager.GetString("msgLayerSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process layer {0}. ähnelt.
        /// </summary>
        internal static string msgProcess {
            get {
                return ResourceManager.GetString("msgProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process horizon {0}. ähnelt.
        /// </summary>
        internal static string msgProcessReb {
            get {
                return ResourceManager.GetString("msgProcessReb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read {0} file {1}. ähnelt.
        /// </summary>
        internal static string msgReadFile {
            get {
                return ResourceManager.GetString("msgReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} File {1} successfull read. ähnelt.
        /// </summary>
        internal static string msgSuccessRead {
            get {
                return ResourceManager.GetString("msgSuccessRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TIN with {0} Triangles created. ähnelt.
        /// </summary>
        internal static string msgTINConv {
            get {
                return ResourceManager.GetString("msgTINConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create IFC and write file {0}. ähnelt.
        /// </summary>
        internal static string msgWriteFile {
            get {
                return ResourceManager.GetString("msgWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IFC wrote to file {0}. ähnelt.
        /// </summary>
        internal static string msgWriteSuccess {
            get {
                return ResourceManager.GetString("msgWriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read data ähnelt.
        /// </summary>
        internal static string process {
            get {
                return ResourceManager.GetString("process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terrain contains vertical faces ähnelt.
        /// </summary>
        internal static string rb3D {
            get {
                return ResourceManager.GetString("rb3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At terrain center ähnelt.
        /// </summary>
        internal static string rbCtr {
            get {
                return ResourceManager.GetString("rbCtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die custom ähnelt.
        /// </summary>
        internal static string rbCust {
            get {
                return ResourceManager.GetString("rbCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read Faces ähnelt.
        /// </summary>
        internal static string rbFaces {
            get {
                return ResourceManager.GetString("rbFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read Points / Lines ähnelt.
        /// </summary>
        internal static string rbIndPoly {
            get {
                return ResourceManager.GetString("rbIndPoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At terrain maximum ähnelt.
        /// </summary>
        internal static string rbMax {
            get {
                return ResourceManager.GetString("rbMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At terrain minimum ähnelt.
        /// </summary>
        internal static string rbMin {
            get {
                return ResourceManager.GetString("rbMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At system origin ähnelt.
        /// </summary>
        internal static string rbSys {
            get {
                return ResourceManager.GetString("rbSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read ähnelt.
        /// </summary>
        internal static string read {
            get {
                return ResourceManager.GetString("read", resourceCulture);
            }
        }
    }
}
