//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFCTerrain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IFCTerrain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Choose file.
        /// </summary>
        internal static string btnChoose {
            get {
                return ResourceManager.GetString("btnChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to TIN.
        /// </summary>
        internal static string btnConvert {
            get {
                return ResourceManager.GetString("btnConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Input.
        /// </summary>
        internal static string btnInput {
            get {
                return ResourceManager.GetString("btnInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Output.
        /// </summary>
        internal static string btnOutput {
            get {
                return ResourceManager.GetString("btnOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Read.
        /// </summary>
        internal static string btnRead {
            get {
                return ResourceManager.GetString("btnRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Read file.
        /// </summary>
        internal static string btnReadFile {
            get {
                return ResourceManager.GetString("btnReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Write IFC.
        /// </summary>
        internal static string btnWrite {
            get {
                return ResourceManager.GetString("btnWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Points on Breaklines.
        /// </summary>
        internal static string chkReplace {
            get {
                return ResourceManager.GetString("chkReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-Origin = 0.
        /// </summary>
        internal static string chkZ {
            get {
                return ResourceManager.GetString("chkZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DD_BIM_LOGO {
            get {
                object obj = ResourceManager.GetObject("DD_BIM_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0} is not readable..
        /// </summary>
        internal static string errFileNotReadable {
            get {
                return ResourceManager.GetString("errFileNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Layer contains no line data..
        /// </summary>
        internal static string errNoLineData {
            get {
                return ResourceManager.GetString("errNoLineData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} contains no TIN..
        /// </summary>
        internal static string errNoTIN {
            get {
                return ResourceManager.GetString("errNoTIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIN in File {0} contains no readable data..
        /// </summary>
        internal static string errNoTINData {
            get {
                return ResourceManager.GetString("errNoTINData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string gpEditor {
            get {
                return ResourceManager.GetString("gpEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Terrain.
        /// </summary>
        internal static string gpFile {
            get {
                return ResourceManager.GetString("gpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string gpMenu {
            get {
                return ResourceManager.GetString("gpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string gpMsg {
            get {
                return ResourceManager.GetString("gpMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site origin.
        /// </summary>
        internal static string gpOrigin {
            get {
                return ResourceManager.GetString("gpOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff31507\deff0\stshfdbch31506\stshfloch31506\stshfhich31506\stshfbi31507\deflang1033\deflangfe1033\themelang1031\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f39\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}
        ///{\f44\fbidi \fswiss\fcharset134\fprq2{\*\panose 020b0503020204020204}Microsoft YaHei;}{\f87\fbidi \fswiss\fcharset134\fprq2 @Microsoft YaHei;}{\flomajor\f31500\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IFCTerrain {
            get {
                return ResourceManager.GetString("IFCTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string lblCount {
            get {
                return ResourceManager.GetString("lblCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with distance.
        /// </summary>
        internal static string lblDist {
            get {
                return ResourceManager.GetString("lblDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extent.
        /// </summary>
        internal static string lblExtent {
            get {
                return ResourceManager.GetString("lblExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        internal static string lblFamily {
            get {
                return ResourceManager.GetString("lblFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string lblFile {
            get {
                return ResourceManager.GetString("lblFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name.
        /// </summary>
        internal static string lblGiven {
            get {
                return ResourceManager.GetString("lblGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizon:.
        /// </summary>
        internal static string lblHorizon {
            get {
                return ResourceManager.GetString("lblHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal point distance.
        /// </summary>
        internal static string lblPtDist {
            get {
                return ResourceManager.GetString("lblPtDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        internal static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points: {0} Lines: {1} Faces: {2}.
        /// </summary>
        internal static string msgCount {
            get {
                return ResourceManager.GetString("msgCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizon successfull read..
        /// </summary>
        internal static string msgHorizonSuccess {
            get {
                return ResourceManager.GetString("msgHorizonSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer successfull read..
        /// </summary>
        internal static string msgLayerSucces {
            get {
                return ResourceManager.GetString("msgLayerSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process layer {0}..
        /// </summary>
        internal static string msgProcess {
            get {
                return ResourceManager.GetString("msgProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process horizon {0}..
        /// </summary>
        internal static string msgProcessReb {
            get {
                return ResourceManager.GetString("msgProcessReb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read {0} file {1}..
        /// </summary>
        internal static string msgReadFile {
            get {
                return ResourceManager.GetString("msgReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} File {1} successfull read..
        /// </summary>
        internal static string msgSuccessRead {
            get {
                return ResourceManager.GetString("msgSuccessRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIN with {0} Triangles created..
        /// </summary>
        internal static string msgTINConv {
            get {
                return ResourceManager.GetString("msgTINConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create IFC and write file {0}..
        /// </summary>
        internal static string msgWriteFile {
            get {
                return ResourceManager.GetString("msgWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC wrote to file {0}..
        /// </summary>
        internal static string msgWriteSuccess {
            get {
                return ResourceManager.GetString("msgWriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read data.
        /// </summary>
        internal static string process {
            get {
                return ResourceManager.GetString("process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain contains vertical faces.
        /// </summary>
        internal static string rb3D {
            get {
                return ResourceManager.GetString("rb3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At terrain center.
        /// </summary>
        internal static string rbCtr {
            get {
                return ResourceManager.GetString("rbCtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom.
        /// </summary>
        internal static string rbCust {
            get {
                return ResourceManager.GetString("rbCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Faces.
        /// </summary>
        internal static string rbFaces {
            get {
                return ResourceManager.GetString("rbFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Points / Lines.
        /// </summary>
        internal static string rbIndPoly {
            get {
                return ResourceManager.GetString("rbIndPoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At terrain maximum.
        /// </summary>
        internal static string rbMax {
            get {
                return ResourceManager.GetString("rbMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At terrain minimum.
        /// </summary>
        internal static string rbMin {
            get {
                return ResourceManager.GetString("rbMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At system origin.
        /// </summary>
        internal static string rbSys {
            get {
                return ResourceManager.GetString("rbSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string read {
            get {
                return ResourceManager.GetString("read", resourceCulture);
            }
        }
    }
}
